#include <boost/system/error_code.hpp>
#include <prerror.h>
#include <sslerr.h>
#include <secerr.h>

#include "error/nss.hpp"

namespace mist
{

namespace
{

class nss_error_category : public boost::system::error_category
{
  const char *name() const noexcept
  {
    return "nss";
  }
  
  std::string message(int ev) const
  {
    switch (ev) {
    case PR_OUT_OF_MEMORY_ERROR:
      return "PR_OUT_OF_MEMORY_ERROR";
    case PR_BAD_DESCRIPTOR_ERROR:
      return "PR_BAD_DESCRIPTOR_ERROR";
    case PR_WOULD_BLOCK_ERROR:
      return "PR_WOULD_BLOCK_ERROR";
    case PR_ACCESS_FAULT_ERROR:
      return "PR_ACCESS_FAULT_ERROR";
    case PR_INVALID_METHOD_ERROR:
      return "PR_INVALID_METHOD_ERROR";
    case PR_ILLEGAL_ACCESS_ERROR:
      return "PR_ILLEGAL_ACCESS_ERROR";
    case PR_UNKNOWN_ERROR:
      return "PR_UNKNOWN_ERROR";
    case PR_PENDING_INTERRUPT_ERROR:
      return "PR_PENDING_INTERRUPT_ERROR";
    case PR_NOT_IMPLEMENTED_ERROR:
      return "PR_NOT_IMPLEMENTED_ERROR";
    case PR_IO_ERROR:
      return "PR_IO_ERROR";
    case PR_IO_TIMEOUT_ERROR:
      return "PR_IO_TIMEOUT_ERROR";
    case PR_IO_PENDING_ERROR:
      return "PR_IO_PENDING_ERROR";
    case PR_DIRECTORY_OPEN_ERROR:
      return "PR_DIRECTORY_OPEN_ERROR";
    case PR_INVALID_ARGUMENT_ERROR:
      return "PR_INVALID_ARGUMENT_ERROR";
    case PR_ADDRESS_NOT_AVAILABLE_ERROR:
      return "PR_ADDRESS_NOT_AVAILABLE_ERROR";
    case PR_ADDRESS_NOT_SUPPORTED_ERROR:
      return "PR_ADDRESS_NOT_SUPPORTED_ERROR";
    case PR_IS_CONNECTED_ERROR:
      return "PR_IS_CONNECTED_ERROR";
    case PR_BAD_ADDRESS_ERROR:
      return "PR_BAD_ADDRESS_ERROR";
    case PR_ADDRESS_IN_USE_ERROR:
      return "PR_ADDRESS_IN_USE_ERROR";
    case PR_CONNECT_REFUSED_ERROR:
      return "PR_CONNECT_REFUSED_ERROR";
    case PR_NETWORK_UNREACHABLE_ERROR:
      return "PR_NETWORK_UNREACHABLE_ERROR";
    case PR_CONNECT_TIMEOUT_ERROR:
      return "PR_CONNECT_TIMEOUT_ERROR";
    case PR_NOT_CONNECTED_ERROR:
      return "PR_NOT_CONNECTED_ERROR";
    case PR_LOAD_LIBRARY_ERROR:
      return "PR_LOAD_LIBRARY_ERROR";
    case PR_UNLOAD_LIBRARY_ERROR:
      return "PR_UNLOAD_LIBRARY_ERROR";
    case PR_FIND_SYMBOL_ERROR:
      return "PR_FIND_SYMBOL_ERROR";
    case PR_INSUFFICIENT_RESOURCES_ERROR:
      return "PR_INSUFFICIENT_RESOURCES_ERROR";
    case PR_DIRECTORY_LOOKUP_ERROR:
      return "PR_DIRECTORY_LOOKUP_ERROR";
    case PR_TPD_RANGE_ERROR:
      return "PR_TPD_RANGE_ERROR";
    case PR_PROC_DESC_TABLE_FULL_ERROR:
      return "PR_PROC_DESC_TABLE_FULL_ERROR";
    case PR_SYS_DESC_TABLE_FULL_ERROR:
      return "PR_SYS_DESC_TABLE_FULL_ERROR";
    case PR_NOT_SOCKET_ERROR:
      return "PR_NOT_SOCKET_ERROR";
    case PR_NOT_TCP_SOCKET_ERROR:
      return "PR_NOT_TCP_SOCKET_ERROR";
    case PR_SOCKET_ADDRESS_IS_BOUND_ERROR:
      return "PR_SOCKET_ADDRESS_IS_BOUND_ERROR";
    case PR_NO_ACCESS_RIGHTS_ERROR:
      return "PR_NO_ACCESS_RIGHTS_ERROR";
    case PR_OPERATION_NOT_SUPPORTED_ERROR:
      return "PR_OPERATION_NOT_SUPPORTED_ERROR";
    case PR_PROTOCOL_NOT_SUPPORTED_ERROR:
      return "PR_PROTOCOL_NOT_SUPPORTED_ERROR";
    case PR_REMOTE_FILE_ERROR:
      return "PR_REMOTE_FILE_ERROR";
    case PR_BUFFER_OVERFLOW_ERROR:
      return "PR_BUFFER_OVERFLOW_ERROR";
    case PR_CONNECT_RESET_ERROR:
      return "PR_CONNECT_RESET_ERROR";
    case PR_RANGE_ERROR:
      return "PR_RANGE_ERROR";
    case PR_DEADLOCK_ERROR:
      return "PR_DEADLOCK_ERROR";
    case PR_FILE_IS_LOCKED_ERROR:
      return "PR_FILE_IS_LOCKED_ERROR";
    case PR_FILE_TOO_BIG_ERROR:
      return "PR_FILE_TOO_BIG_ERROR";
    case PR_NO_DEVICE_SPACE_ERROR:
      return "PR_NO_DEVICE_SPACE_ERROR";
    case PR_PIPE_ERROR:
      return "PR_PIPE_ERROR";
    case PR_NO_SEEK_DEVICE_ERROR:
      return "PR_NO_SEEK_DEVICE_ERROR";
    case PR_IS_DIRECTORY_ERROR:
      return "PR_IS_DIRECTORY_ERROR";
    case PR_LOOP_ERROR:
      return "PR_LOOP_ERROR";
    case PR_NAME_TOO_LONG_ERROR:
      return "PR_NAME_TOO_LONG_ERROR";
    case PR_FILE_NOT_FOUND_ERROR:
      return "PR_FILE_NOT_FOUND_ERROR";
    case PR_NOT_DIRECTORY_ERROR:
      return "PR_NOT_DIRECTORY_ERROR";
    case PR_READ_ONLY_FILESYSTEM_ERROR:
      return "PR_READ_ONLY_FILESYSTEM_ERROR";
    case PR_DIRECTORY_NOT_EMPTY_ERROR:
      return "PR_DIRECTORY_NOT_EMPTY_ERROR";
    case PR_FILESYSTEM_MOUNTED_ERROR:
      return "PR_FILESYSTEM_MOUNTED_ERROR";
    case PR_NOT_SAME_DEVICE_ERROR:
      return "PR_NOT_SAME_DEVICE_ERROR";
    case PR_DIRECTORY_CORRUPTED_ERROR:
      return "PR_DIRECTORY_CORRUPTED_ERROR";
    case PR_FILE_EXISTS_ERROR:
      return "PR_FILE_EXISTS_ERROR";
    case PR_MAX_DIRECTORY_ENTRIES_ERROR:
      return "PR_MAX_DIRECTORY_ENTRIES_ERROR";
    case PR_INVALID_DEVICE_STATE_ERROR:
      return "PR_INVALID_DEVICE_STATE_ERROR";
    case PR_DEVICE_IS_LOCKED_ERROR:
      return "PR_DEVICE_IS_LOCKED_ERROR";
    case PR_NO_MORE_FILES_ERROR:
      return "PR_NO_MORE_FILES_ERROR";
    case PR_END_OF_FILE_ERROR:
      return "PR_END_OF_FILE_ERROR";
    case PR_FILE_SEEK_ERROR:
      return "PR_FILE_SEEK_ERROR";
    case PR_FILE_IS_BUSY_ERROR:
      return "PR_FILE_IS_BUSY_ERROR";
    case PR_OPERATION_ABORTED_ERROR:
      return "PR_OPERATION_ABORTED_ERROR";
    case PR_IN_PROGRESS_ERROR:
      return "PR_IN_PROGRESS_ERROR";
    case PR_ALREADY_INITIATED_ERROR:
      return "PR_ALREADY_INITIATED_ERROR";
    case PR_GROUP_EMPTY_ERROR:
      return "PR_GROUP_EMPTY_ERROR";
    case PR_INVALID_STATE_ERROR:
      return "PR_INVALID_STATE_ERROR";
    case PR_NETWORK_DOWN_ERROR:
      return "PR_NETWORK_DOWN_ERROR";
    case PR_SOCKET_SHUTDOWN_ERROR:
      return "PR_SOCKET_SHUTDOWN_ERROR";
    case PR_CONNECT_ABORTED_ERROR:
      return "PR_CONNECT_ABORTED_ERROR";
    case PR_HOST_UNREACHABLE_ERROR:
      return "PR_HOST_UNREACHABLE_ERROR";
    case PR_LIBRARY_NOT_LOADED_ERROR:
      return "PR_LIBRARY_NOT_LOADED_ERROR";
    case PR_CALL_ONCE_ERROR:
      return "PR_CALL_ONCE_ERROR";
    case SSL_ERROR_EXPORT_ONLY_SERVER:
      return "SSL_ERROR_EXPORT_ONLY_SERVER";
    case SSL_ERROR_US_ONLY_SERVER:
      return "SSL_ERROR_US_ONLY_SERVER";
    case SSL_ERROR_NO_CYPHER_OVERLAP:
      return "SSL_ERROR_NO_CYPHER_OVERLAP";
    case SSL_ERROR_NO_CERTIFICATE:
      return "SSL_ERROR_NO_CERTIFICATE";
    case SSL_ERROR_BAD_CERTIFICATE:
      return "SSL_ERROR_BAD_CERTIFICATE";
    case SSL_ERROR_UNUSED_5:
      return "SSL_ERROR_UNUSED_5";
    case SSL_ERROR_BAD_CLIENT:
      return "SSL_ERROR_BAD_CLIENT";
    case SSL_ERROR_BAD_SERVER:
      return "SSL_ERROR_BAD_SERVER";
    case SSL_ERROR_UNSUPPORTED_CERTIFICATE_TYPE:
      return "SSL_ERROR_UNSUPPORTED_CERTIFICATE_TYPE";
    case SSL_ERROR_UNSUPPORTED_VERSION:
      return "SSL_ERROR_UNSUPPORTED_VERSION";
    case SSL_ERROR_UNUSED_10:
      return "SSL_ERROR_UNUSED_10";
    case SSL_ERROR_WRONG_CERTIFICATE:
      return "SSL_ERROR_WRONG_CERTIFICATE";
    case SSL_ERROR_BAD_CERT_DOMAIN:
      return "SSL_ERROR_BAD_CERT_DOMAIN";
    case SSL_ERROR_POST_WARNING:
      return "SSL_ERROR_POST_WARNING";
    case SSL_ERROR_SSL2_DISABLED:
      return "SSL_ERROR_SSL2_DISABLED";
    case SSL_ERROR_BAD_MAC_READ:
      return "SSL_ERROR_BAD_MAC_READ";
    case SSL_ERROR_BAD_MAC_ALERT:
      return "SSL_ERROR_BAD_MAC_ALERT";
    case SSL_ERROR_BAD_CERT_ALERT:
      return "SSL_ERROR_BAD_CERT_ALERT";
    case SSL_ERROR_REVOKED_CERT_ALERT:
      return "SSL_ERROR_REVOKED_CERT_ALERT";
    case SSL_ERROR_EXPIRED_CERT_ALERT:
      return "SSL_ERROR_EXPIRED_CERT_ALERT";
    case SSL_ERROR_SSL_DISABLED:
      return "SSL_ERROR_SSL_DISABLED";
    case SSL_ERROR_FORTEZZA_PQG:
      return "SSL_ERROR_FORTEZZA_PQG";
    case SSL_ERROR_UNKNOWN_CIPHER_SUITE:
      return "SSL_ERROR_UNKNOWN_CIPHER_SUITE";
    case SSL_ERROR_NO_CIPHERS_SUPPORTED:
      return "SSL_ERROR_NO_CIPHERS_SUPPORTED";
    case SSL_ERROR_BAD_BLOCK_PADDING:
      return "SSL_ERROR_BAD_BLOCK_PADDING";
    case SSL_ERROR_RX_RECORD_TOO_LONG:
      return "SSL_ERROR_RX_RECORD_TOO_LONG";
    case SSL_ERROR_TX_RECORD_TOO_LONG:
      return "SSL_ERROR_TX_RECORD_TOO_LONG";
    case SSL_ERROR_RX_MALFORMED_HELLO_REQUEST:
      return "SSL_ERROR_RX_MALFORMED_HELLO_REQUEST";
    case SSL_ERROR_RX_MALFORMED_CLIENT_HELLO:
      return "SSL_ERROR_RX_MALFORMED_CLIENT_HELLO";
    case SSL_ERROR_RX_MALFORMED_SERVER_HELLO:
      return "SSL_ERROR_RX_MALFORMED_SERVER_HELLO";
    case SSL_ERROR_RX_MALFORMED_CERTIFICATE:
      return "SSL_ERROR_RX_MALFORMED_CERTIFICATE";
    case SSL_ERROR_RX_MALFORMED_SERVER_KEY_EXCH:
      return "SSL_ERROR_RX_MALFORMED_SERVER_KEY_EXCH";
    case SSL_ERROR_RX_MALFORMED_CERT_REQUEST:
      return "SSL_ERROR_RX_MALFORMED_CERT_REQUEST";
    case SSL_ERROR_RX_MALFORMED_HELLO_DONE:
      return "SSL_ERROR_RX_MALFORMED_HELLO_DONE";
    case SSL_ERROR_RX_MALFORMED_CERT_VERIFY:
      return "SSL_ERROR_RX_MALFORMED_CERT_VERIFY";
    case SSL_ERROR_RX_MALFORMED_CLIENT_KEY_EXCH:
      return "SSL_ERROR_RX_MALFORMED_CLIENT_KEY_EXCH";
    case SSL_ERROR_RX_MALFORMED_FINISHED:
      return "SSL_ERROR_RX_MALFORMED_FINISHED";
    case SSL_ERROR_RX_MALFORMED_CHANGE_CIPHER:
      return "SSL_ERROR_RX_MALFORMED_CHANGE_CIPHER";
    case SSL_ERROR_RX_MALFORMED_ALERT:
      return "SSL_ERROR_RX_MALFORMED_ALERT";
    case SSL_ERROR_RX_MALFORMED_HANDSHAKE:
      return "SSL_ERROR_RX_MALFORMED_HANDSHAKE";
    case SSL_ERROR_RX_MALFORMED_APPLICATION_DATA:
      return "SSL_ERROR_RX_MALFORMED_APPLICATION_DATA";
    case SSL_ERROR_RX_UNEXPECTED_HELLO_REQUEST:
      return "SSL_ERROR_RX_UNEXPECTED_HELLO_REQUEST";
    case SSL_ERROR_RX_UNEXPECTED_CLIENT_HELLO:
      return "SSL_ERROR_RX_UNEXPECTED_CLIENT_HELLO";
    case SSL_ERROR_RX_UNEXPECTED_SERVER_HELLO:
      return "SSL_ERROR_RX_UNEXPECTED_SERVER_HELLO";
    case SSL_ERROR_RX_UNEXPECTED_CERTIFICATE:
      return "SSL_ERROR_RX_UNEXPECTED_CERTIFICATE";
    case SSL_ERROR_RX_UNEXPECTED_SERVER_KEY_EXCH:
      return "SSL_ERROR_RX_UNEXPECTED_SERVER_KEY_EXCH";
    case SSL_ERROR_RX_UNEXPECTED_CERT_REQUEST:
      return "SSL_ERROR_RX_UNEXPECTED_CERT_REQUEST";
    case SSL_ERROR_RX_UNEXPECTED_HELLO_DONE:
      return "SSL_ERROR_RX_UNEXPECTED_HELLO_DONE";
    case SSL_ERROR_RX_UNEXPECTED_CERT_VERIFY:
      return "SSL_ERROR_RX_UNEXPECTED_CERT_VERIFY";
    case SSL_ERROR_RX_UNEXPECTED_CLIENT_KEY_EXCH:
      return "SSL_ERROR_RX_UNEXPECTED_CLIENT_KEY_EXCH";
    case SSL_ERROR_RX_UNEXPECTED_FINISHED:
      return "SSL_ERROR_RX_UNEXPECTED_FINISHED";
    case SSL_ERROR_RX_UNEXPECTED_CHANGE_CIPHER:
      return "SSL_ERROR_RX_UNEXPECTED_CHANGE_CIPHER";
    case SSL_ERROR_RX_UNEXPECTED_ALERT:
      return "SSL_ERROR_RX_UNEXPECTED_ALERT";
    case SSL_ERROR_RX_UNEXPECTED_HANDSHAKE:
      return "SSL_ERROR_RX_UNEXPECTED_HANDSHAKE";
    case SSL_ERROR_RX_UNEXPECTED_APPLICATION_DATA:
      return "SSL_ERROR_RX_UNEXPECTED_APPLICATION_DATA";
    case SSL_ERROR_RX_UNKNOWN_RECORD_TYPE:
      return "SSL_ERROR_RX_UNKNOWN_RECORD_TYPE";
    case SSL_ERROR_RX_UNKNOWN_HANDSHAKE:
      return "SSL_ERROR_RX_UNKNOWN_HANDSHAKE";
    case SSL_ERROR_RX_UNKNOWN_ALERT:
      return "SSL_ERROR_RX_UNKNOWN_ALERT";
    case SSL_ERROR_CLOSE_NOTIFY_ALERT:
      return "SSL_ERROR_CLOSE_NOTIFY_ALERT";
    case SSL_ERROR_HANDSHAKE_UNEXPECTED_ALERT:
      return "SSL_ERROR_HANDSHAKE_UNEXPECTED_ALERT";
    case SSL_ERROR_DECOMPRESSION_FAILURE_ALERT:
      return "SSL_ERROR_DECOMPRESSION_FAILURE_ALERT";
    case SSL_ERROR_HANDSHAKE_FAILURE_ALERT:
      return "SSL_ERROR_HANDSHAKE_FAILURE_ALERT";
    case SSL_ERROR_ILLEGAL_PARAMETER_ALERT:
      return "SSL_ERROR_ILLEGAL_PARAMETER_ALERT";
    case SSL_ERROR_UNSUPPORTED_CERT_ALERT:
      return "SSL_ERROR_UNSUPPORTED_CERT_ALERT";
    case SSL_ERROR_CERTIFICATE_UNKNOWN_ALERT:
      return "SSL_ERROR_CERTIFICATE_UNKNOWN_ALERT";
    case SSL_ERROR_GENERATE_RANDOM_FAILURE:
      return "SSL_ERROR_GENERATE_RANDOM_FAILURE";
    case SSL_ERROR_SIGN_HASHES_FAILURE:
      return "SSL_ERROR_SIGN_HASHES_FAILURE";
    case SSL_ERROR_EXTRACT_PUBLIC_KEY_FAILURE:
      return "SSL_ERROR_EXTRACT_PUBLIC_KEY_FAILURE";
    case SSL_ERROR_SERVER_KEY_EXCHANGE_FAILURE:
      return "SSL_ERROR_SERVER_KEY_EXCHANGE_FAILURE";
    case SSL_ERROR_CLIENT_KEY_EXCHANGE_FAILURE:
      return "SSL_ERROR_CLIENT_KEY_EXCHANGE_FAILURE";
    case SSL_ERROR_ENCRYPTION_FAILURE:
      return "SSL_ERROR_ENCRYPTION_FAILURE";
    case SSL_ERROR_DECRYPTION_FAILURE:
      return "SSL_ERROR_DECRYPTION_FAILURE";
    case SSL_ERROR_SOCKET_WRITE_FAILURE:
      return "SSL_ERROR_SOCKET_WRITE_FAILURE";
    case SSL_ERROR_MD5_DIGEST_FAILURE:
      return "SSL_ERROR_MD5_DIGEST_FAILURE";
    case SSL_ERROR_SHA_DIGEST_FAILURE:
      return "SSL_ERROR_SHA_DIGEST_FAILURE";
    case SSL_ERROR_MAC_COMPUTATION_FAILURE:
      return "SSL_ERROR_MAC_COMPUTATION_FAILURE";
    case SSL_ERROR_SYM_KEY_CONTEXT_FAILURE:
      return "SSL_ERROR_SYM_KEY_CONTEXT_FAILURE";
    case SSL_ERROR_SYM_KEY_UNWRAP_FAILURE:
      return "SSL_ERROR_SYM_KEY_UNWRAP_FAILURE";
    case SSL_ERROR_PUB_KEY_SIZE_LIMIT_EXCEEDED:
      return "SSL_ERROR_PUB_KEY_SIZE_LIMIT_EXCEEDED";
    case SSL_ERROR_IV_PARAM_FAILURE:
      return "SSL_ERROR_IV_PARAM_FAILURE";
    case SSL_ERROR_INIT_CIPHER_SUITE_FAILURE:
      return "SSL_ERROR_INIT_CIPHER_SUITE_FAILURE";
    case SSL_ERROR_SESSION_KEY_GEN_FAILURE:
      return "SSL_ERROR_SESSION_KEY_GEN_FAILURE";
    case SSL_ERROR_NO_SERVER_KEY_FOR_ALG:
      return "SSL_ERROR_NO_SERVER_KEY_FOR_ALG";
    case SSL_ERROR_TOKEN_INSERTION_REMOVAL:
      return "SSL_ERROR_TOKEN_INSERTION_REMOVAL";
    case SSL_ERROR_TOKEN_SLOT_NOT_FOUND:
      return "SSL_ERROR_TOKEN_SLOT_NOT_FOUND";
    case SSL_ERROR_NO_COMPRESSION_OVERLAP:
      return "SSL_ERROR_NO_COMPRESSION_OVERLAP";
    case SSL_ERROR_HANDSHAKE_NOT_COMPLETED:
      return "SSL_ERROR_HANDSHAKE_NOT_COMPLETED";
    case SSL_ERROR_BAD_HANDSHAKE_HASH_VALUE:
      return "SSL_ERROR_BAD_HANDSHAKE_HASH_VALUE";
    case SSL_ERROR_CERT_KEA_MISMATCH:
      return "SSL_ERROR_CERT_KEA_MISMATCH";
    case SSL_ERROR_NO_TRUSTED_SSL_CLIENT_CA:
      return "SSL_ERROR_NO_TRUSTED_SSL_CLIENT_CA";
    case SSL_ERROR_SESSION_NOT_FOUND:
      return "SSL_ERROR_SESSION_NOT_FOUND";
    case SSL_ERROR_DECRYPTION_FAILED_ALERT:
      return "SSL_ERROR_DECRYPTION_FAILED_ALERT";
    case SSL_ERROR_RECORD_OVERFLOW_ALERT:
      return "SSL_ERROR_RECORD_OVERFLOW_ALERT";
    case SSL_ERROR_UNKNOWN_CA_ALERT:
      return "SSL_ERROR_UNKNOWN_CA_ALERT";
    case SSL_ERROR_ACCESS_DENIED_ALERT:
      return "SSL_ERROR_ACCESS_DENIED_ALERT";
    case SSL_ERROR_DECODE_ERROR_ALERT:
      return "SSL_ERROR_DECODE_ERROR_ALERT";
    case SSL_ERROR_DECRYPT_ERROR_ALERT:
      return "SSL_ERROR_DECRYPT_ERROR_ALERT";
    case SSL_ERROR_EXPORT_RESTRICTION_ALERT:
      return "SSL_ERROR_EXPORT_RESTRICTION_ALERT";
    case SSL_ERROR_PROTOCOL_VERSION_ALERT:
      return "SSL_ERROR_PROTOCOL_VERSION_ALERT";
    case SSL_ERROR_INSUFFICIENT_SECURITY_ALERT:
      return "SSL_ERROR_INSUFFICIENT_SECURITY_ALERT";
    case SSL_ERROR_INTERNAL_ERROR_ALERT:
      return "SSL_ERROR_INTERNAL_ERROR_ALERT";
    case SSL_ERROR_USER_CANCELED_ALERT:
      return "SSL_ERROR_USER_CANCELED_ALERT";
    case SSL_ERROR_NO_RENEGOTIATION_ALERT:
      return "SSL_ERROR_NO_RENEGOTIATION_ALERT";
    case SSL_ERROR_SERVER_CACHE_NOT_CONFIGURED:
      return "SSL_ERROR_SERVER_CACHE_NOT_CONFIGURED";
    case SSL_ERROR_UNSUPPORTED_EXTENSION_ALERT:
      return "SSL_ERROR_UNSUPPORTED_EXTENSION_ALERT";
    case SSL_ERROR_CERTIFICATE_UNOBTAINABLE_ALERT:
      return "SSL_ERROR_CERTIFICATE_UNOBTAINABLE_ALERT";
    case SSL_ERROR_UNRECOGNIZED_NAME_ALERT:
      return "SSL_ERROR_UNRECOGNIZED_NAME_ALERT";
    case SSL_ERROR_BAD_CERT_STATUS_RESPONSE_ALERT:
      return "SSL_ERROR_BAD_CERT_STATUS_RESPONSE_ALERT";
    case SSL_ERROR_BAD_CERT_HASH_VALUE_ALERT:
      return "SSL_ERROR_BAD_CERT_HASH_VALUE_ALERT";
    case SSL_ERROR_RX_UNEXPECTED_NEW_SESSION_TICKET:
      return "SSL_ERROR_RX_UNEXPECTED_NEW_SESSION_TICKET";
    case SSL_ERROR_RX_MALFORMED_NEW_SESSION_TICKET:
      return "SSL_ERROR_RX_MALFORMED_NEW_SESSION_TICKET";
    case SSL_ERROR_DECOMPRESSION_FAILURE:
      return "SSL_ERROR_DECOMPRESSION_FAILURE";
    case SSL_ERROR_RENEGOTIATION_NOT_ALLOWED:
      return "SSL_ERROR_RENEGOTIATION_NOT_ALLOWED";
    case SSL_ERROR_UNSAFE_NEGOTIATION:
      return "SSL_ERROR_UNSAFE_NEGOTIATION";
    case SSL_ERROR_RX_UNEXPECTED_UNCOMPRESSED_RECORD:
      return "SSL_ERROR_RX_UNEXPECTED_UNCOMPRESSED_RECORD";
    case SSL_ERROR_WEAK_SERVER_EPHEMERAL_DH_KEY:
      return "SSL_ERROR_WEAK_SERVER_EPHEMERAL_DH_KEY";
    case SSL_ERROR_NEXT_PROTOCOL_DATA_INVALID:
      return "SSL_ERROR_NEXT_PROTOCOL_DATA_INVALID";
    case SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_SSL2:
      return "SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_SSL2";
    case SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_SERVERS:
      return "SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_SERVERS";
    case SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_CLIENTS:
      return "SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_CLIENTS";
    case SSL_ERROR_INVALID_VERSION_RANGE:
      return "SSL_ERROR_INVALID_VERSION_RANGE";
    case SSL_ERROR_CIPHER_DISALLOWED_FOR_VERSION:
      return "SSL_ERROR_CIPHER_DISALLOWED_FOR_VERSION";
    case SSL_ERROR_RX_MALFORMED_HELLO_VERIFY_REQUEST:
      return "SSL_ERROR_RX_MALFORMED_HELLO_VERIFY_REQUEST";
    case SSL_ERROR_RX_UNEXPECTED_HELLO_VERIFY_REQUEST:
      return "SSL_ERROR_RX_UNEXPECTED_HELLO_VERIFY_REQUEST";
    case SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_VERSION:
      return "SSL_ERROR_FEATURE_NOT_SUPPORTED_FOR_VERSION";
    case SSL_ERROR_RX_UNEXPECTED_CERT_STATUS:
      return "SSL_ERROR_RX_UNEXPECTED_CERT_STATUS";
    case SSL_ERROR_UNSUPPORTED_HASH_ALGORITHM:
      return "SSL_ERROR_UNSUPPORTED_HASH_ALGORITHM";
    case SSL_ERROR_DIGEST_FAILURE:
      return "SSL_ERROR_DIGEST_FAILURE";
    case SSL_ERROR_INCORRECT_SIGNATURE_ALGORITHM:
      return "SSL_ERROR_INCORRECT_SIGNATURE_ALGORITHM";
    case SSL_ERROR_NEXT_PROTOCOL_NO_CALLBACK:
      return "SSL_ERROR_NEXT_PROTOCOL_NO_CALLBACK";
    case SSL_ERROR_NEXT_PROTOCOL_NO_PROTOCOL:
      return "SSL_ERROR_NEXT_PROTOCOL_NO_PROTOCOL";
    case SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT:
      return "SSL_ERROR_INAPPROPRIATE_FALLBACK_ALERT";
    // case SSL_ERROR_WEAK_SERVER_CERT_KEY:
      // return "SSL_ERROR_WEAK_SERVER_CERT_KEY";
    // case SSL_ERROR_RX_SHORT_DTLS_READ:
      // return "SSL_ERROR_RX_SHORT_DTLS_READ";
    // case SSL_ERROR_NO_SUPPORTED_SIGNATURE_ALGORITHM:
      // return "SSL_ERROR_NO_SUPPORTED_SIGNATURE_ALGORITHM";
    // case SSL_ERROR_UNSUPPORTED_SIGNATURE_ALGORITHM:
      // return "SSL_ERROR_UNSUPPORTED_SIGNATURE_ALGORITHM";
    // case SSL_ERROR_MISSING_EXTENDED_MASTER_SECRET:
      // return "SSL_ERROR_MISSING_EXTENDED_MASTER_SECRET";
    // case SSL_ERROR_UNEXPECTED_EXTENDED_MASTER_SECRET:
      // return "SSL_ERROR_UNEXPECTED_EXTENDED_MASTER_SECRET";
    // case SSL_ERROR_RX_MALFORMED_KEY_SHARE:
      // return "SSL_ERROR_RX_MALFORMED_KEY_SHARE";
    // case SSL_ERROR_MISSING_KEY_SHARE:
      // return "SSL_ERROR_MISSING_KEY_SHARE";
    // case SSL_ERROR_RX_MALFORMED_ECDHE_KEY_SHARE:
      // return "SSL_ERROR_RX_MALFORMED_ECDHE_KEY_SHARE";
    // case SSL_ERROR_RX_MALFORMED_DHE_KEY_SHARE:
      // return "SSL_ERROR_RX_MALFORMED_DHE_KEY_SHARE";
    // case SSL_ERROR_RX_UNEXPECTED_ENCRYPTED_EXTENSIONS:
      // return "SSL_ERROR_RX_UNEXPECTED_ENCRYPTED_EXTENSIONS";
    // case SSL_ERROR_MISSING_EXTENSION_ALERT:
      // return "SSL_ERROR_MISSING_EXTENSION_ALERT";
    // case SSL_ERROR_KEY_EXCHANGE_FAILURE:
      // return "SSL_ERROR_KEY_EXCHANGE_FAILURE";
    // case SSL_ERROR_EXTENSION_DISALLOWED_FOR_VERSION:
      // return "SSL_ERROR_EXTENSION_DISALLOWED_FOR_VERSION";
    // case SSL_ERROR_RX_MALFORMED_ENCRYPTED_EXTENSIONS:
      // return "SSL_ERROR_RX_MALFORMED_ENCRYPTED_EXTENSIONS";
    // case SSL_ERROR_MALFORMED_PRE_SHARED_KEY:
      // return "SSL_ERROR_MALFORMED_PRE_SHARED_KEY";
    case SEC_ERROR_IO:
      return "SEC_ERROR_IO";
    case SEC_ERROR_LIBRARY_FAILURE:
      return "SEC_ERROR_LIBRARY_FAILURE";
    case SEC_ERROR_BAD_DATA:
      return "SEC_ERROR_BAD_DATA";
    case SEC_ERROR_OUTPUT_LEN:
      return "SEC_ERROR_OUTPUT_LEN";
    case SEC_ERROR_INPUT_LEN:
      return "SEC_ERROR_INPUT_LEN";
    case SEC_ERROR_INVALID_ARGS:
      return "SEC_ERROR_INVALID_ARGS";
    case SEC_ERROR_INVALID_ALGORITHM:
      return "SEC_ERROR_INVALID_ALGORITHM";
    case SEC_ERROR_INVALID_AVA:
      return "SEC_ERROR_INVALID_AVA";
    case SEC_ERROR_INVALID_TIME:
      return "SEC_ERROR_INVALID_TIME";
    case SEC_ERROR_BAD_DER:
      return "SEC_ERROR_BAD_DER";
    case SEC_ERROR_BAD_SIGNATURE:
      return "SEC_ERROR_BAD_SIGNATURE";
    case SEC_ERROR_EXPIRED_CERTIFICATE:
      return "SEC_ERROR_EXPIRED_CERTIFICATE";
    case SEC_ERROR_REVOKED_CERTIFICATE:
      return "SEC_ERROR_REVOKED_CERTIFICATE";
    case SEC_ERROR_UNKNOWN_ISSUER:
      return "SEC_ERROR_UNKNOWN_ISSUER";
    case SEC_ERROR_BAD_KEY:
      return "SEC_ERROR_BAD_KEY";
    case SEC_ERROR_BAD_PASSWORD:
      return "SEC_ERROR_BAD_PASSWORD";
    case SEC_ERROR_RETRY_PASSWORD:
      return "SEC_ERROR_RETRY_PASSWORD";
    case SEC_ERROR_NO_NODELOCK:
      return "SEC_ERROR_NO_NODELOCK";
    case SEC_ERROR_BAD_DATABASE:
      return "SEC_ERROR_BAD_DATABASE";
    case SEC_ERROR_NO_MEMORY:
      return "SEC_ERROR_NO_MEMORY";
    case SEC_ERROR_UNTRUSTED_ISSUER:
      return "SEC_ERROR_UNTRUSTED_ISSUER";
    case SEC_ERROR_UNTRUSTED_CERT:
      return "SEC_ERROR_UNTRUSTED_CERT";
    case SEC_ERROR_DUPLICATE_CERT:
      return "SEC_ERROR_DUPLICATE_CERT";
    case SEC_ERROR_DUPLICATE_CERT_NAME:
      return "SEC_ERROR_DUPLICATE_CERT_NAME";
    case SEC_ERROR_ADDING_CERT:
      return "SEC_ERROR_ADDING_CERT";
    case SEC_ERROR_FILING_KEY:
      return "SEC_ERROR_FILING_KEY";
    case SEC_ERROR_NO_KEY:
      return "SEC_ERROR_NO_KEY";
    case SEC_ERROR_CERT_VALID:
      return "SEC_ERROR_CERT_VALID";
    case SEC_ERROR_CERT_NOT_VALID:
      return "SEC_ERROR_CERT_NOT_VALID";
    case SEC_ERROR_CERT_NO_RESPONSE:
      return "SEC_ERROR_CERT_NO_RESPONSE";
    case SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE:
      return "SEC_ERROR_EXPIRED_ISSUER_CERTIFICATE";
    case SEC_ERROR_CRL_EXPIRED:
      return "SEC_ERROR_CRL_EXPIRED";
    case SEC_ERROR_CRL_BAD_SIGNATURE:
      return "SEC_ERROR_CRL_BAD_SIGNATURE";
    case SEC_ERROR_CRL_INVALID:
      return "SEC_ERROR_CRL_INVALID";
    case SEC_ERROR_EXTENSION_VALUE_INVALID:
      return "SEC_ERROR_EXTENSION_VALUE_INVALID";
    case SEC_ERROR_EXTENSION_NOT_FOUND:
      return "SEC_ERROR_EXTENSION_NOT_FOUND";
    case SEC_ERROR_CA_CERT_INVALID:
      return "SEC_ERROR_CA_CERT_INVALID";
    case SEC_ERROR_PATH_LEN_CONSTRAINT_INVALID:
      return "SEC_ERROR_PATH_LEN_CONSTRAINT_INVALID";
    case SEC_ERROR_CERT_USAGES_INVALID:
      return "SEC_ERROR_CERT_USAGES_INVALID";
    case SEC_INTERNAL_ONLY:
      return "SEC_INTERNAL_ONLY";
    case SEC_ERROR_INVALID_KEY:
      return "SEC_ERROR_INVALID_KEY";
    case SEC_ERROR_UNKNOWN_CRITICAL_EXTENSION:
      return "SEC_ERROR_UNKNOWN_CRITICAL_EXTENSION";
    case SEC_ERROR_OLD_CRL:
      return "SEC_ERROR_OLD_CRL";
    case SEC_ERROR_NO_EMAIL_CERT:
      return "SEC_ERROR_NO_EMAIL_CERT";
    case SEC_ERROR_NO_RECIPIENT_CERTS_QUERY:
      return "SEC_ERROR_NO_RECIPIENT_CERTS_QUERY";
    case SEC_ERROR_NOT_A_RECIPIENT:
      return "SEC_ERROR_NOT_A_RECIPIENT";
    case SEC_ERROR_PKCS7_KEYALG_MISMATCH:
      return "SEC_ERROR_PKCS7_KEYALG_MISMATCH";
    case SEC_ERROR_PKCS7_BAD_SIGNATURE:
      return "SEC_ERROR_PKCS7_BAD_SIGNATURE";
    case SEC_ERROR_UNSUPPORTED_KEYALG:
      return "SEC_ERROR_UNSUPPORTED_KEYALG";
    case SEC_ERROR_DECRYPTION_DISALLOWED:
      return "SEC_ERROR_DECRYPTION_DISALLOWED";
    case XP_SEC_FORTEZZA_BAD_CARD:
      return "XP_SEC_FORTEZZA_BAD_CARD";
    case XP_SEC_FORTEZZA_NO_CARD:
      return "XP_SEC_FORTEZZA_NO_CARD";
    case XP_SEC_FORTEZZA_NONE_SELECTED:
      return "XP_SEC_FORTEZZA_NONE_SELECTED";
    case XP_SEC_FORTEZZA_MORE_INFO:
      return "XP_SEC_FORTEZZA_MORE_INFO";
    case XP_SEC_FORTEZZA_PERSON_NOT_FOUND:
      return "XP_SEC_FORTEZZA_PERSON_NOT_FOUND";
    case XP_SEC_FORTEZZA_NO_MORE_INFO:
      return "XP_SEC_FORTEZZA_NO_MORE_INFO";
    case XP_SEC_FORTEZZA_BAD_PIN:
      return "XP_SEC_FORTEZZA_BAD_PIN";
    case XP_SEC_FORTEZZA_PERSON_ERROR:
      return "XP_SEC_FORTEZZA_PERSON_ERROR";
    case SEC_ERROR_NO_KRL:
      return "SEC_ERROR_NO_KRL";
    case SEC_ERROR_KRL_EXPIRED:
      return "SEC_ERROR_KRL_EXPIRED";
    case SEC_ERROR_KRL_BAD_SIGNATURE:
      return "SEC_ERROR_KRL_BAD_SIGNATURE";
    case SEC_ERROR_REVOKED_KEY:
      return "SEC_ERROR_REVOKED_KEY";
    case SEC_ERROR_KRL_INVALID:
      return "SEC_ERROR_KRL_INVALID";
    case SEC_ERROR_NEED_RANDOM:
      return "SEC_ERROR_NEED_RANDOM";
    case SEC_ERROR_NO_MODULE:
      return "SEC_ERROR_NO_MODULE";
    case SEC_ERROR_NO_TOKEN:
      return "SEC_ERROR_NO_TOKEN";
    case SEC_ERROR_READ_ONLY:
      return "SEC_ERROR_READ_ONLY";
    case SEC_ERROR_NO_SLOT_SELECTED:
      return "SEC_ERROR_NO_SLOT_SELECTED";
    case SEC_ERROR_CERT_NICKNAME_COLLISION:
      return "SEC_ERROR_CERT_NICKNAME_COLLISION";
    case SEC_ERROR_KEY_NICKNAME_COLLISION:
      return "SEC_ERROR_KEY_NICKNAME_COLLISION";
    case SEC_ERROR_SAFE_NOT_CREATED:
      return "SEC_ERROR_SAFE_NOT_CREATED";
    case SEC_ERROR_BAGGAGE_NOT_CREATED:
      return "SEC_ERROR_BAGGAGE_NOT_CREATED";
    case XP_JAVA_REMOVE_PRINCIPAL_ERROR:
      return "XP_JAVA_REMOVE_PRINCIPAL_ERROR";
    case XP_JAVA_DELETE_PRIVILEGE_ERROR:
      return "XP_JAVA_DELETE_PRIVILEGE_ERROR";
    case XP_JAVA_CERT_NOT_EXISTS_ERROR:
      return "XP_JAVA_CERT_NOT_EXISTS_ERROR";
    case SEC_ERROR_BAD_EXPORT_ALGORITHM:
      return "SEC_ERROR_BAD_EXPORT_ALGORITHM";
    case SEC_ERROR_EXPORTING_CERTIFICATES:
      return "SEC_ERROR_EXPORTING_CERTIFICATES";
    case SEC_ERROR_IMPORTING_CERTIFICATES:
      return "SEC_ERROR_IMPORTING_CERTIFICATES";
    case SEC_ERROR_PKCS12_DECODING_PFX:
      return "SEC_ERROR_PKCS12_DECODING_PFX";
    case SEC_ERROR_PKCS12_INVALID_MAC:
      return "SEC_ERROR_PKCS12_INVALID_MAC";
    case SEC_ERROR_PKCS12_UNSUPPORTED_MAC_ALGORITHM:
      return "SEC_ERROR_PKCS12_UNSUPPORTED_MAC_ALGORITHM";
    case SEC_ERROR_PKCS12_UNSUPPORTED_TRANSPORT_MODE:
      return "SEC_ERROR_PKCS12_UNSUPPORTED_TRANSPORT_MODE";
    case SEC_ERROR_PKCS12_CORRUPT_PFX_STRUCTURE:
      return "SEC_ERROR_PKCS12_CORRUPT_PFX_STRUCTURE";
    case SEC_ERROR_PKCS12_UNSUPPORTED_PBE_ALGORITHM:
      return "SEC_ERROR_PKCS12_UNSUPPORTED_PBE_ALGORITHM";
    case SEC_ERROR_PKCS12_UNSUPPORTED_VERSION:
      return "SEC_ERROR_PKCS12_UNSUPPORTED_VERSION";
    case SEC_ERROR_PKCS12_PRIVACY_PASSWORD_INCORRECT:
      return "SEC_ERROR_PKCS12_PRIVACY_PASSWORD_INCORRECT";
    case SEC_ERROR_PKCS12_CERT_COLLISION:
      return "SEC_ERROR_PKCS12_CERT_COLLISION";
    case SEC_ERROR_USER_CANCELLED:
      return "SEC_ERROR_USER_CANCELLED";
    case SEC_ERROR_PKCS12_DUPLICATE_DATA:
      return "SEC_ERROR_PKCS12_DUPLICATE_DATA";
    case SEC_ERROR_MESSAGE_SEND_ABORTED:
      return "SEC_ERROR_MESSAGE_SEND_ABORTED";
    case SEC_ERROR_INADEQUATE_KEY_USAGE:
      return "SEC_ERROR_INADEQUATE_KEY_USAGE";
    case SEC_ERROR_INADEQUATE_CERT_TYPE:
      return "SEC_ERROR_INADEQUATE_CERT_TYPE";
    case SEC_ERROR_CERT_ADDR_MISMATCH:
      return "SEC_ERROR_CERT_ADDR_MISMATCH";
    case SEC_ERROR_PKCS12_UNABLE_TO_IMPORT_KEY:
      return "SEC_ERROR_PKCS12_UNABLE_TO_IMPORT_KEY";
    case SEC_ERROR_PKCS12_IMPORTING_CERT_CHAIN:
      return "SEC_ERROR_PKCS12_IMPORTING_CERT_CHAIN";
    case SEC_ERROR_PKCS12_UNABLE_TO_LOCATE_OBJECT_BY_NAME:
      return "SEC_ERROR_PKCS12_UNABLE_TO_LOCATE_OBJECT_BY_NAME";
    case SEC_ERROR_PKCS12_UNABLE_TO_EXPORT_KEY:
      return "SEC_ERROR_PKCS12_UNABLE_TO_EXPORT_KEY";
    case SEC_ERROR_PKCS12_UNABLE_TO_WRITE:
      return "SEC_ERROR_PKCS12_UNABLE_TO_WRITE";
    case SEC_ERROR_PKCS12_UNABLE_TO_READ:
      return "SEC_ERROR_PKCS12_UNABLE_TO_READ";
    case SEC_ERROR_PKCS12_KEY_DATABASE_NOT_INITIALIZED:
      return "SEC_ERROR_PKCS12_KEY_DATABASE_NOT_INITIALIZED";
    case SEC_ERROR_KEYGEN_FAIL:
      return "SEC_ERROR_KEYGEN_FAIL";
    case SEC_ERROR_INVALID_PASSWORD:
      return "SEC_ERROR_INVALID_PASSWORD";
    case SEC_ERROR_RETRY_OLD_PASSWORD:
      return "SEC_ERROR_RETRY_OLD_PASSWORD";
    case SEC_ERROR_BAD_NICKNAME:
      return "SEC_ERROR_BAD_NICKNAME";
    case SEC_ERROR_NOT_FORTEZZA_ISSUER:
      return "SEC_ERROR_NOT_FORTEZZA_ISSUER";
    case SEC_ERROR_CANNOT_MOVE_SENSITIVE_KEY:
      return "SEC_ERROR_CANNOT_MOVE_SENSITIVE_KEY";
    case SEC_ERROR_JS_INVALID_MODULE_NAME:
      return "SEC_ERROR_JS_INVALID_MODULE_NAME";
    case SEC_ERROR_JS_INVALID_DLL:
      return "SEC_ERROR_JS_INVALID_DLL";
    case SEC_ERROR_JS_ADD_MOD_FAILURE:
      return "SEC_ERROR_JS_ADD_MOD_FAILURE";
    case SEC_ERROR_JS_DEL_MOD_FAILURE:
      return "SEC_ERROR_JS_DEL_MOD_FAILURE";
    case SEC_ERROR_OLD_KRL:
      return "SEC_ERROR_OLD_KRL";
    case SEC_ERROR_CKL_CONFLICT:
      return "SEC_ERROR_CKL_CONFLICT";
    case SEC_ERROR_CERT_NOT_IN_NAME_SPACE:
      return "SEC_ERROR_CERT_NOT_IN_NAME_SPACE";
    case SEC_ERROR_KRL_NOT_YET_VALID:
      return "SEC_ERROR_KRL_NOT_YET_VALID";
    case SEC_ERROR_CRL_NOT_YET_VALID:
      return "SEC_ERROR_CRL_NOT_YET_VALID";
    case SEC_ERROR_UNKNOWN_CERT:
      return "SEC_ERROR_UNKNOWN_CERT";
    case SEC_ERROR_UNKNOWN_SIGNER:
      return "SEC_ERROR_UNKNOWN_SIGNER";
    case SEC_ERROR_CERT_BAD_ACCESS_LOCATION:
      return "SEC_ERROR_CERT_BAD_ACCESS_LOCATION";
    case SEC_ERROR_OCSP_UNKNOWN_RESPONSE_TYPE:
      return "SEC_ERROR_OCSP_UNKNOWN_RESPONSE_TYPE";
    case SEC_ERROR_OCSP_BAD_HTTP_RESPONSE:
      return "SEC_ERROR_OCSP_BAD_HTTP_RESPONSE";
    case SEC_ERROR_OCSP_MALFORMED_REQUEST:
      return "SEC_ERROR_OCSP_MALFORMED_REQUEST";
    case SEC_ERROR_OCSP_SERVER_ERROR:
      return "SEC_ERROR_OCSP_SERVER_ERROR";
    case SEC_ERROR_OCSP_TRY_SERVER_LATER:
      return "SEC_ERROR_OCSP_TRY_SERVER_LATER";
    case SEC_ERROR_OCSP_REQUEST_NEEDS_SIG:
      return "SEC_ERROR_OCSP_REQUEST_NEEDS_SIG";
    case SEC_ERROR_OCSP_UNAUTHORIZED_REQUEST:
      return "SEC_ERROR_OCSP_UNAUTHORIZED_REQUEST";
    case SEC_ERROR_OCSP_UNKNOWN_RESPONSE_STATUS:
      return "SEC_ERROR_OCSP_UNKNOWN_RESPONSE_STATUS";
    case SEC_ERROR_OCSP_UNKNOWN_CERT:
      return "SEC_ERROR_OCSP_UNKNOWN_CERT";
    case SEC_ERROR_OCSP_NOT_ENABLED:
      return "SEC_ERROR_OCSP_NOT_ENABLED";
    case SEC_ERROR_OCSP_NO_DEFAULT_RESPONDER:
      return "SEC_ERROR_OCSP_NO_DEFAULT_RESPONDER";
    case SEC_ERROR_OCSP_MALFORMED_RESPONSE:
      return "SEC_ERROR_OCSP_MALFORMED_RESPONSE";
    case SEC_ERROR_OCSP_UNAUTHORIZED_RESPONSE:
      return "SEC_ERROR_OCSP_UNAUTHORIZED_RESPONSE";
    case SEC_ERROR_OCSP_FUTURE_RESPONSE:
      return "SEC_ERROR_OCSP_FUTURE_RESPONSE";
    case SEC_ERROR_OCSP_OLD_RESPONSE:
      return "SEC_ERROR_OCSP_OLD_RESPONSE";
    case SEC_ERROR_DIGEST_NOT_FOUND:
      return "SEC_ERROR_DIGEST_NOT_FOUND";
    case SEC_ERROR_UNSUPPORTED_MESSAGE_TYPE:
      return "SEC_ERROR_UNSUPPORTED_MESSAGE_TYPE";
    case SEC_ERROR_MODULE_STUCK:
      return "SEC_ERROR_MODULE_STUCK";
    case SEC_ERROR_BAD_TEMPLATE:
      return "SEC_ERROR_BAD_TEMPLATE";
    case SEC_ERROR_CRL_NOT_FOUND:
      return "SEC_ERROR_CRL_NOT_FOUND";
    case SEC_ERROR_REUSED_ISSUER_AND_SERIAL:
      return "SEC_ERROR_REUSED_ISSUER_AND_SERIAL";
    case SEC_ERROR_BUSY:
      return "SEC_ERROR_BUSY";
    case SEC_ERROR_EXTRA_INPUT:
      return "SEC_ERROR_EXTRA_INPUT";
    case SEC_ERROR_UNSUPPORTED_ELLIPTIC_CURVE:
      return "SEC_ERROR_UNSUPPORTED_ELLIPTIC_CURVE";
    case SEC_ERROR_UNSUPPORTED_EC_POINT_FORM:
      return "SEC_ERROR_UNSUPPORTED_EC_POINT_FORM";
    case SEC_ERROR_UNRECOGNIZED_OID:
      return "SEC_ERROR_UNRECOGNIZED_OID";
    case SEC_ERROR_OCSP_INVALID_SIGNING_CERT:
      return "SEC_ERROR_OCSP_INVALID_SIGNING_CERT";
    case SEC_ERROR_REVOKED_CERTIFICATE_CRL:
      return "SEC_ERROR_REVOKED_CERTIFICATE_CRL";
    case SEC_ERROR_REVOKED_CERTIFICATE_OCSP:
      return "SEC_ERROR_REVOKED_CERTIFICATE_OCSP";
    case SEC_ERROR_CRL_INVALID_VERSION:
      return "SEC_ERROR_CRL_INVALID_VERSION";
    case SEC_ERROR_CRL_V1_CRITICAL_EXTENSION:
      return "SEC_ERROR_CRL_V1_CRITICAL_EXTENSION";
    case SEC_ERROR_CRL_UNKNOWN_CRITICAL_EXTENSION:
      return "SEC_ERROR_CRL_UNKNOWN_CRITICAL_EXTENSION";
    case SEC_ERROR_UNKNOWN_OBJECT_TYPE:
      return "SEC_ERROR_UNKNOWN_OBJECT_TYPE";
    case SEC_ERROR_INCOMPATIBLE_PKCS11:
      return "SEC_ERROR_INCOMPATIBLE_PKCS11";
    case SEC_ERROR_NO_EVENT:
      return "SEC_ERROR_NO_EVENT";
    case SEC_ERROR_CRL_ALREADY_EXISTS:
      return "SEC_ERROR_CRL_ALREADY_EXISTS";
    case SEC_ERROR_NOT_INITIALIZED:
      return "SEC_ERROR_NOT_INITIALIZED";
    case SEC_ERROR_TOKEN_NOT_LOGGED_IN:
      return "SEC_ERROR_TOKEN_NOT_LOGGED_IN";
    case SEC_ERROR_OCSP_RESPONDER_CERT_INVALID:
      return "SEC_ERROR_OCSP_RESPONDER_CERT_INVALID";
    case SEC_ERROR_OCSP_BAD_SIGNATURE:
      return "SEC_ERROR_OCSP_BAD_SIGNATURE";
    case SEC_ERROR_OUT_OF_SEARCH_LIMITS:
      return "SEC_ERROR_OUT_OF_SEARCH_LIMITS";
    case SEC_ERROR_INVALID_POLICY_MAPPING:
      return "SEC_ERROR_INVALID_POLICY_MAPPING";
    case SEC_ERROR_POLICY_VALIDATION_FAILED:
      return "SEC_ERROR_POLICY_VALIDATION_FAILED";
    case SEC_ERROR_UNKNOWN_AIA_LOCATION_TYPE:
      return "SEC_ERROR_UNKNOWN_AIA_LOCATION_TYPE";
    case SEC_ERROR_BAD_HTTP_RESPONSE:
      return "SEC_ERROR_BAD_HTTP_RESPONSE";
    case SEC_ERROR_BAD_LDAP_RESPONSE:
      return "SEC_ERROR_BAD_LDAP_RESPONSE";
    case SEC_ERROR_FAILED_TO_ENCODE_DATA:
      return "SEC_ERROR_FAILED_TO_ENCODE_DATA";
    case SEC_ERROR_BAD_INFO_ACCESS_LOCATION:
      return "SEC_ERROR_BAD_INFO_ACCESS_LOCATION";
    case SEC_ERROR_LIBPKIX_INTERNAL:
      return "SEC_ERROR_LIBPKIX_INTERNAL";
    case SEC_ERROR_PKCS11_GENERAL_ERROR:
      return "SEC_ERROR_PKCS11_GENERAL_ERROR";
    case SEC_ERROR_PKCS11_FUNCTION_FAILED:
      return "SEC_ERROR_PKCS11_FUNCTION_FAILED";
    case SEC_ERROR_PKCS11_DEVICE_ERROR:
      return "SEC_ERROR_PKCS11_DEVICE_ERROR";
    case SEC_ERROR_BAD_INFO_ACCESS_METHOD:
      return "SEC_ERROR_BAD_INFO_ACCESS_METHOD";
    case SEC_ERROR_CRL_IMPORT_FAILED:
      return "SEC_ERROR_CRL_IMPORT_FAILED";
    case SEC_ERROR_EXPIRED_PASSWORD:
      return "SEC_ERROR_EXPIRED_PASSWORD";
    case SEC_ERROR_LOCKED_PASSWORD:
      return "SEC_ERROR_LOCKED_PASSWORD";
    case SEC_ERROR_UNKNOWN_PKCS11_ERROR:
      return "SEC_ERROR_UNKNOWN_PKCS11_ERROR";
    case SEC_ERROR_BAD_CRL_DP_URL:
      return "SEC_ERROR_BAD_CRL_DP_URL";
    case SEC_ERROR_CERT_SIGNATURE_ALGORITHM_DISABLED:
      return "SEC_ERROR_CERT_SIGNATURE_ALGORITHM_DISABLED";
    case SEC_ERROR_LEGACY_DATABASE:
      return "SEC_ERROR_LEGACY_DATABASE";
    case SEC_ERROR_APPLICATION_CALLBACK_ERROR:
      return "SEC_ERROR_APPLICATION_CALLBACK_ERROR";
    // case NSS_ERROR_NO_ERROR:
      // return "NSS_ERROR_NO_ERROR";
    // case NSS_ERROR_INTERNAL_ERROR:
      // return "NSS_ERROR_INTERNAL_ERROR";
    // case NSS_ERROR_NO_MEMORY:
      // return "NSS_ERROR_NO_MEMORY";
    // case NSS_ERROR_INVALID_POINTER:
      // return "NSS_ERROR_INVALID_POINTER";
    // case NSS_ERROR_INVALID_ARENA:
      // return "NSS_ERROR_INVALID_ARENA";
    // case NSS_ERROR_INVALID_ARENA_MARK:
      // return "NSS_ERROR_INVALID_ARENA_MARK";
    // case NSS_ERROR_DUPLICATE_POINTER:
      // return "NSS_ERROR_DUPLICATE_POINTER";
    // case NSS_ERROR_POINTER_NOT_REGISTERED:
      // return "NSS_ERROR_POINTER_NOT_REGISTERED";
    // case NSS_ERROR_TRACKER_NOT_EMPTY:
      // return "NSS_ERROR_TRACKER_NOT_EMPTY";
    // case NSS_ERROR_TRACKER_NOT_INITIALIZED:
      // return "NSS_ERROR_TRACKER_NOT_INITIALIZED";
    // case NSS_ERROR_ARENA_MARKED_BY_ANOTHER_THREAD:
      // return "NSS_ERROR_ARENA_MARKED_BY_ANOTHER_THREAD";
    // case NSS_ERROR_VALUE_TOO_LARGE:
      // return "NSS_ERROR_VALUE_TOO_LARGE";
    // case NSS_ERROR_UNSUPPORTED_TYPE:
      // return "NSS_ERROR_UNSUPPORTED_TYPE";
    // case NSS_ERROR_BUFFER_TOO_SHORT:
      // return "NSS_ERROR_BUFFER_TOO_SHORT";
    // case NSS_ERROR_INVALID_ATOB_CONTEXT:
      // return "NSS_ERROR_INVALID_ATOB_CONTEXT";
    // case NSS_ERROR_INVALID_BASE64:
      // return "NSS_ERROR_INVALID_BASE64";
    // case NSS_ERROR_INVALID_BTOA_CONTEXT:
      // return "NSS_ERROR_INVALID_BTOA_CONTEXT";
    // case NSS_ERROR_INVALID_ITEM:
      // return "NSS_ERROR_INVALID_ITEM";
    // case NSS_ERROR_INVALID_STRING:
      // return "NSS_ERROR_INVALID_STRING";
    // case NSS_ERROR_INVALID_ASN1ENCODER:
      // return "NSS_ERROR_INVALID_ASN1ENCODER";
    // case NSS_ERROR_INVALID_ASN1DECODER:
      // return "NSS_ERROR_INVALID_ASN1DECODER";
    // case NSS_ERROR_INVALID_BER:
      // return "NSS_ERROR_INVALID_BER";
    // case NSS_ERROR_INVALID_ATAV:
      // return "NSS_ERROR_INVALID_ATAV";
    // case NSS_ERROR_INVALID_ARGUMENT:
      // return "NSS_ERROR_INVALID_ARGUMENT";
    // case NSS_ERROR_INVALID_UTF8:
      // return "NSS_ERROR_INVALID_UTF8";
    // case NSS_ERROR_INVALID_NSSOID:
      // return "NSS_ERROR_INVALID_NSSOID";
    // case NSS_ERROR_UNKNOWN_ATTRIBUTE:
      // return "NSS_ERROR_UNKNOWN_ATTRIBUTE";
    // case NSS_ERROR_NOT_FOUND:
      // return "NSS_ERROR_NOT_FOUND";
    // case NSS_ERROR_INVALID_PASSWORD:
      // return "NSS_ERROR_INVALID_PASSWORD";
    // case NSS_ERROR_USER_CANCELED:
      // return "NSS_ERROR_USER_CANCELED";
    // case NSS_ERROR_MAXIMUM_FOUND:
      // return "NSS_ERROR_MAXIMUM_FOUND";
    // case NSS_ERROR_CERTIFICATE_ISSUER_NOT_FOUND:
      // return "NSS_ERROR_CERTIFICATE_ISSUER_NOT_FOUND";
    // case NSS_ERROR_CERTIFICATE_IN_CACHE:
      // return "NSS_ERROR_CERTIFICATE_IN_CACHE";
    // case NSS_ERROR_HASH_COLLISION:
      // return "NSS_ERROR_HASH_COLLISION";
    // case NSS_ERROR_DEVICE_ERROR:
      // return "NSS_ERROR_DEVICE_ERROR";
    // case NSS_ERROR_INVALID_CERTIFICATE:
      // return "NSS_ERROR_INVALID_CERTIFICATE";
    // case NSS_ERROR_BUSY:
      // return "NSS_ERROR_BUSY";
    // case NSS_ERROR_ALREADY_INITIALIZED:
      // return "NSS_ERROR_ALREADY_INITIALIZED";
    // case NSS_ERROR_PKCS11:
      // return "NSS_ERROR_PKCS11";
    default:
      return "Unknown nss error " + std::to_string(ev);
    }
  }
} instance;

} // namespace

MistConnApi
const boost::system::error_category &nss_category() noexcept
{
  return instance;
}

MistConnApi
boost::system::error_code make_nss_error(PRErrorCode ev)
{
  return boost::system::error_code(ev, nss_category());
}

MistConnApi
boost::system::error_code make_nss_error()
{
  return boost::system::error_code(PR_GetError(), nss_category());
}

} // namespace mist
